"""add_certificate_table

Revision ID: de79c1af8b0e
Revises: c92bee2de0f6
Create Date: 2023-05-17 09:52:51.647714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de79c1af8b0e'
down_revision = 'c92bee2de0f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('user_id', sa.CHAR(32), nullable=False),
    sa.Column('course_id', sa.CHAR(32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    # ### end Alembic commands ###
