"""courses

Revision ID: f092a5b7b311
Revises: de79c1af8b0e
Create Date: 2023-05-17 10:19:11.928391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f092a5b7b311'
down_revision = 'de79c1af8b0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('user_id', sa.CHAR(32), nullable=False),
    sa.Column('course_id', sa.CHAR(32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processes')
    # ### end Alembic commands ###
